### ISSUE TITLE
Add sample for ASP.NET Core web applications

### ISSUE THREAD

**Issue by AlexZeitler** [BoasE/BE.CQRS#5]
Goals:

- Show `CommandBus` usage
- Show CQRS Bootstrapping in ASP.NET Core 

@BoasE Is folder name `2_ASPNET_Core/AspNetCoreSample`  ok?

**Comment by AlexZeitler** [comment]
@BoasE I've added the `CQRSBooter` to the ASP.NET Core sample  as discussed, but when starting the sample, I get these errors: 

```
Configuring Services...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Driver.Core, Version=2.4.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

Adding the `MongoDb.Driver.Core` `2.4.4` to the `AspNetCoreSample` project fixed it, but shouldn't the package reference be already correct by adding the `BE.CQRS.Data.MongoDb` package?

**Comment by BoasE** [comment]
Yes you are right I assume I was missing to add the mongorefrence in the nugetspec
